site_name: Pembahasan OSK 2015
pages:
- [index.md, Home]
- ["Soal 01.md", Soal 01]
- ["Soal 02.md", Soal 02]
- ["Soal 03.md", Soal 03]
- ["Soal 04.md", Soal 04]
- ["Soal 05.md", Soal 05]
- ["Soal 06.md", Soal 06]
- ["Soal 07.md", Soal 07]
- ["Soal 08.md", Soal 08]
- ["Soal 09.md", Soal 09]
- ["Soal 10.md", Soal 10]
- ["Soal 11.md", Soal 11]
